export const QUICK_VALIDATION_MIN_CHARS = 20;
export const QUICK_VALIDATION_MAX_CHARS = 2000;

export type QuickVerdict = "worth-testing" | "narrow-first" | "rewrite-first";
export type DomainStatus = "unchecked" | "available" | "registered" | "unknown";

export interface QuickNameIdea {
  name: string;
  domain: string;
  status: DomainStatus;
}

export interface QuickValidationResult {
  verdict: QuickVerdict;
  verdictLabel: string;
  rationale: string;
  likelyPayer: string;
  problemHypothesis: string;
  currentAlternatives: string[];
  firstTest: string;
  passThreshold: string;
  risks: string[];
  sharperPositioning: string;
  searchQueries: string[];
  nameIdeas: QuickNameIdea[];
  evidenceStatus: { level: "hypothesis"; label: string; detail: string; };
  provider: "deterministic-local-v1" | "openai";
}

type HostedResponse = { output_text?: string };
const STOP_WORDS = new Set(["about","after","again","also","another","app","around","because","build","building","could","from","have","idea","into","just","like","make","making","people","platform","product","service","that","their","them","then","there","these","they","this","tool","using","want","where","which","with","would","your"]);

function truncate(value:string,length:number){return value.length<=length?value:`${value.slice(0,Math.max(0,length-1)).trimEnd()}…`;}
export function normalizeQuickIdea(raw:string){return raw.replace(/\s+/g," ").trim();}
export function assertQuickIdea(raw:string){const idea=normalizeQuickIdea(raw);if(idea.length<QUICK_VALIDATION_MIN_CHARS)throw new Error(`Describe the idea in at least ${QUICK_VALIDATION_MIN_CHARS} characters.`);if(idea.length>QUICK_VALIDATION_MAX_CHARS)throw new Error(`Keep the quick check under ${QUICK_VALIDATION_MAX_CHARS} characters.`);return idea;}
function cleanSegment(value:string){return truncate(value.replace(/\b(who|that|which)\b.*$/i,"").replace(/\s+/g," ").trim(),80);}
function extractTarget(idea:string){for(const pattern of [/\b(?:app|tool|platform|service|software)\s+for\s+([^,.!?;]{3,90})/i,/\bfor\s+([^,.!?;]{3,90})/i,/\bhelp(?:s|ing)?\s+([^,.!?;]{3,90}?)\s+(?:to|with|avoid|reduce|save)\b/i]){const match=idea.match(pattern);if(match?.[1])return cleanSegment(match[1]);}return "a narrowly defined group of people who repeatedly feel this problem";}
function extractProblem(idea:string){for(const pattern of [/\b(?:struggle(?:s|ing)?\s+with|problem\s+of|pain\s+of|avoid|reduce)\s+([^,.!?;]{5,130})/i,/\b(?:save|saving)\s+([^,.!?;]{5,130})/i,/\b(?:so that|to)\s+([^,.!?;]{8,130})/i]){const match=idea.match(pattern);if(match?.[1])return truncate(match[1].trim(),130);}return truncate(idea,130);}
function meaningfulTokens(idea:string){return Array.from(new Set(idea.toLowerCase().replace(/[^a-z0-9\s-]/g," ").split(/\s+/).map(token=>token.replace(/^-+|-+$/g,"")).filter(token=>token.length>=4&&token.length<=18&&!STOP_WORDS.has(token))));}
function titleCase(value:string){return value.replace(/(^|[-\s])([a-z])/g,(_,prefix:string,letter:string)=>`${prefix}${letter.toUpperCase()}`);}
export function sanitizeDomainLabel(value:string){return value.toLowerCase().replace(/[^a-z0-9-]/g,"").replace(/^-+|-+$/g,"").slice(0,54);}
function buildNameIdeas(idea:string):QuickNameIdea[]{const [a="signal",b="pilot",c="proof"]=meaningfulTokens(idea);const raw=[`${a}${b??"pilot"}`,`${a}proof`,`${a}signal`,`${b??a}pilot`,`${c??a}loop`];const seen=new Set<string>();const ideas:QuickNameIdea[]=[];for(const candidate of raw){const label=sanitizeDomainLabel(candidate);if(label.length<3||seen.has(label))continue;seen.add(label);ideas.push({name:titleCase(label),domain:`${label}.com`,status:"unchecked"});if(ideas.length===4)break;}return ideas;}
function hasSpecificAudience(idea:string){return /\bfor\s+[^,.!?;]{3,70}/i.test(idea)||/\b(help|helps|helping)\s+[^,.!?;]{3,70}\s+(to|with|avoid|reduce|save)\b/i.test(idea);}
function hasProblemLanguage(idea:string){return /\b(problem|pain|struggle|waste|slow|expensive|manual|frustrat|avoid|reduce|save|replace|difficult|hard|miss|lose)\w*/i.test(idea);}
function hasOutcomeLanguage(idea:string){return /\b(save|reduce|increase|find|book|sell|buy|track|compare|automate|generate|plan|manage|organize|monitor|prevent|improve|discover)\w*/i.test(idea);}
function localVerdict(idea:string):{verdict:QuickVerdict;label:string;rationale:string}{const audience=hasSpecificAudience(idea),problem=hasProblemLanguage(idea),outcome=hasOutcomeLanguage(idea);if(audience&&(problem||outcome))return{verdict:"worth-testing",label:"Worth a cheap test",rationale:"The idea names enough of a user or outcome to test demand without building much first. The next job is proving frequency and willingness to pay."};if(audience||problem||outcome)return{verdict:"narrow-first",label:"Narrow it before building",rationale:"There is a usable problem signal, but the buyer, recurring pain, or concrete outcome is still fuzzy. Tighten one of those before writing product code."};return{verdict:"rewrite-first",label:"Too vague to judge yet",rationale:"The description reads more like a solution category than a testable customer problem. Rewrite it around one user, one recurring pain, and one measurable outcome."};}

export function buildLocalQuickValidation(raw:string):QuickValidationResult{const idea=assertQuickIdea(raw),target=extractTarget(idea),problem=extractProblem(idea),verdict=localVerdict(idea);const shortTarget=target==="a narrowly defined group of people who repeatedly feel this problem"?"the first narrow user segment you choose":target;return{verdict:verdict.verdict,verdictLabel:verdict.label,rationale:verdict.rationale,likelyPayer:`Hypothesis: ${shortTarget} may pay if this problem is frequent, painful, and costly enough to justify switching from the current workaround.`,problemHypothesis:`Hypothesis to verify: ${problem}.`,currentAlternatives:["A manual workflow using spreadsheets, notes, email, or messaging","A general-purpose tool that solves only part of the job","Doing nothing because the pain is not frequent or costly enough"],firstTest:`Within 7 days, recruit 10 people matching ${shortTarget}. Offer a concierge/manual version of the outcome before building automation, and ask for a concrete commitment: a paid pilot, deposit, scheduled trial, or second use.`,passThreshold:"Treat the test as promising if at least 3 of 10 users ask to use it again and at least 1 makes a real commitment involving money, time, data, or access. Treat compliments alone as insufficient evidence.",risks:["The problem may be real but too infrequent to support a habit or purchase.","The user and the person who controls the budget may be different people.","Existing workarounds may be annoying but still cheaper than switching."],sharperPositioning:`Start narrower: for ${shortTarget}, solve one repeatable job around “${truncate(problem,90)}” and prove the outcome manually before expanding the product surface.`,searchQueries:[`"${truncate(shortTarget,52)}" "${truncate(problem,52)}"`,`site:reddit.com "${truncate(problem,70)}"`,`"${truncate(shortTarget,58)}" software reviews`,`"${truncate(problem,58)}" alternative`],nameIdeas:buildNameIdeas(idea),evidenceStatus:{level:"hypothesis",label:"No market evidence captured yet",detail:"This is a fast pressure-test, not verified market research. Promote the idea into FounderOS to capture sources, competitors, user statements, and contradictory evidence."},provider:"deterministic-local-v1"};}
function asString(value:unknown,fallback:string){return typeof value==="string"&&value.trim()?value.trim():fallback;}
function asStringArray(value:unknown,fallback:string[],max=6){if(!Array.isArray(value))return fallback;const values=value.filter((item):item is string=>typeof item==="string"&&item.trim().length>0).map(item=>item.trim()).slice(0,max);return values.length?values:fallback;}
function parseHostedResult(output:string,fallback:QuickValidationResult):QuickValidationResult|null{try{const start=output.indexOf("{"),end=output.lastIndexOf("}");if(start<0||end<=start)return null;const value=JSON.parse(output.slice(start,end+1)) as Record<string,unknown>;const verdict=value.verdict;const acceptedVerdict:QuickVerdict=verdict==="worth-testing"||verdict==="narrow-first"||verdict==="rewrite-first"?verdict:fallback.verdict;const names=Array.isArray(value.nameIdeas)?value.nameIdeas:[];const nameIdeas:QuickNameIdea[]=[];for(const item of names){if(!item||typeof item!=="object")continue;const record=item as Record<string,unknown>;const rawDomain=asString(record.domain,asString(record.name,"")).replace(/\.com$/i,"");const label=sanitizeDomainLabel(rawDomain);if(label.length<3)continue;nameIdeas.push({name:asString(record.name,titleCase(label)),domain:`${label}.com`,status:"unchecked"});if(nameIdeas.length===4)break;}return{verdict:acceptedVerdict,verdictLabel:asString(value.verdictLabel,fallback.verdictLabel),rationale:asString(value.rationale,fallback.rationale),likelyPayer:asString(value.likelyPayer,fallback.likelyPayer),problemHypothesis:asString(value.problemHypothesis,fallback.problemHypothesis),currentAlternatives:asStringArray(value.currentAlternatives,fallback.currentAlternatives,5),firstTest:asString(value.firstTest,fallback.firstTest),passThreshold:asString(value.passThreshold,fallback.passThreshold),risks:asStringArray(value.risks,fallback.risks,5),sharperPositioning:asString(value.sharperPositioning,fallback.sharperPositioning),searchQueries:asStringArray(value.searchQueries,fallback.searchQueries,5),nameIdeas:nameIdeas.length?nameIdeas:fallback.nameIdeas,evidenceStatus:fallback.evidenceStatus,provider:"openai"};}catch{return null;}}
async function hostedQuickValidation(idea:string,fallback:QuickValidationResult){const key=process.env.OPENAI_API_KEY;if(!key||process.env.AI_PROVIDER!=="openai"||process.env.QUICK_VALIDATION_HOSTED_AI!=="1")return null;const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${key}`},body:JSON.stringify({model:process.env.OPENAI_MODEL||"gpt-5.6-luna",input:[{role:"system",content:[{type:"input_text",text:"You are FounderOS Quick Validation. Be skeptical, practical, and concise. This is NOT market research: do not claim you searched the web, verified demand, checked competitors, or know that anyone will pay. Treat every market statement as a hypothesis. Return only one JSON object with keys: verdict (worth-testing|narrow-first|rewrite-first), verdictLabel, rationale, likelyPayer, problemHypothesis, currentAlternatives (array), firstTest, passThreshold, risks (array), sharperPositioning, searchQueries (array), nameIdeas (array of objects with name and domain). Keep the first test runnable in seven days with little or no code."}]},{role:"user",content:[{type:"input_text",text:`Idea: ${idea}`}]}]})});if(!response.ok)return null;const data=await response.json() as HostedResponse;if(!data.output_text)return null;return parseHostedResult(data.output_text,fallback);}
export async function runQuickValidation(raw:string):Promise<QuickValidationResult>{const idea=assertQuickIdea(raw),fallback=buildLocalQuickValidation(idea);try{return await hostedQuickValidation(idea,fallback)??fallback;}catch{return fallback;}}
